### ISSUE TITLE
new problem

### ISSUE THREAD

**Issue by Hansxsourse** [ferreirafabio/video2tfrecord#5]
Here are the error info

```
`pi@Hans:~/Desktop/testtrans/video2tfrecord$ python3 test.py 
Total videos found: 2
1 of 1 videos within batch processed:  ./example/input/100998.mp4
Batch 1/2 completed
Writing ./example/output/batch_1_of_2.tfrecords
1 of 1 videos within batch processed:  ./example/input/100999.mp4
Batch 2/2 completed
Writing ./example/output/batch_2_of_2.tfrecords
2018-10-03 23:59:48.840133: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:From /home/pi/.local/lib/python3.6/site-packages/tensorflow/python/training/input.py:187: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/pi/.local/lib/python3.6/site-packages/tensorflow/python/training/input.py:187: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From test.py:106: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
E
======================================================================
ERROR: test_example1 (__main__.Testvideo2tfrecord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/home/pi/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/pi/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3686400 values, but the requested shape has 691200
	 [[{{node Reshape_5}} = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](DecodeRaw_1, Reshape_2/shape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 30, in test_example1
    get_number_of_records(filenames, n_frames))
  File "test.py", line 109, in get_number_of_records
    video = sess_valid.run([image_seq_tensor_val])
  File "/home/pi/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home/pi/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/pi/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/home/pi/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3686400 values, but the requested shape has 691200
	 [[{{node Reshape_5}} = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](DecodeRaw_1, Reshape_2/shape)]]

Caused by op 'Reshape_5', defined at:
  File "test.py", line 123, in <module>
    unittest.main()
  File "/usr/lib/python3.6/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python3.6/unittest/main.py", line 256, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python3.6/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "test.py", line 30, in test_example1
    get_number_of_records(filenames, n_frames))
  File "test.py", line 100, in get_number_of_records
    image_seq_tensor_val = read_and_decode(filename_queue_val, n_frames)
  File "test.py", line 74, in read_and_decode
    image = tf.reshape(image, [1, height, width, num_depth])
  File "/home/pi/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6296, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/pi/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/pi/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/home/pi/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 3686400 values, but the requested shape has 691200
	 [[{{node Reshape_5}} = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](DecodeRaw_1, Reshape_2/shape)]]


----------------------------------------------------------------------
Ran 1 test in 11.783s

FAILED (errors=1)
`
```

I try to use only 2 videos to transform, so no problem with numpy array, but this problem
hope you can help me to solve it
Bet wishes for you and your video2tfrecord

**Comment by ferreirafabio** [comment]
this seems to be an error related to the computation graph. Closing, due to no relevance to video2tfrecord. Please use Stackoverflow or TensorFlow FAQ/documentation for solving your issue.
